config/routes.rb
WalmartTestTask::Application.routes.draw do

  resources :parsers do
    get :parse_walmart, on: :collection
  end
  root :to => 'parsers#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parsers_controller.rb
class ParsersController < ApplicationController
  respond_to :html
  def index
  end

  def parse_walmart
    respond_with parser do |format|
      format.html { render partial: 'parsers/response', locals: { result: parser }, layout: false if request.xhr? }
    end
  end

  private
  def parser
    @parser ||= ParseService.build_document(product_id: params[:product_id], search_string: params[:search_string])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parsers_helper.rb
module ParsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalmartTestTask</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/parsers/_response.html.haml
%div
  = t('.found')
  = result.size
%ul
  - result.each do |r|
    %li= "review -> #{r}"

app/views/parsers/index.html.haml
%h2= "Parser"
%div
  = label_tag('product_id')
  = text_field_tag('product_id')
%div
  = label_tag('search_query')
  = text_field_tag('search_query')
= submit_tag('send')

#response

:javascript
  $(function(){
    new window.Parser({ url: "#{parse_walmart_parsers_path}"})
  })